package io.github.tuxkoh.bcsfe;

import io.github.tuxkoh.bcsfe.core.SaveDocument;

/** Generated from BCData 15.5.0 equipment resources. */
final class TalentOrbNames {
    private TalentOrbNames() {}
    private static final String[] EN = {
        "Attack Up D: Red",
        "Attack Up C: Red",
        "Attack Up B: Red",
        "Attack Up A: Red",
        "Attack Up S: Red",
        "Defense Up D: Red",
        "Defense Up C: Red",
        "Defense Up B: Red",
        "Defense Up A: Red",
        "Defense Up S: Red",
        "Attack Up D: Floating",
        "Attack Up C: Floating",
        "Attack Up B: Floating",
        "Attack Up A: Floating",
        "Attack Up S: Floating",
        "Defense Up D: Floating",
        "Defense Up C: Floating",
        "Defense Up B: Floating",
        "Defense Up A: Floating",
        "Defense Up S: Floating",
        "Attack Up D: Dark",
        "Attack Up C: Dark",
        "Attack Up B: Dark",
        "Attack Up A: Dark",
        "Attack Up S: Dark",
        "Defense Up D: Dark",
        "Defense Up C: Dark",
        "Defense Up B: Dark",
        "Defense Up A: Dark",
        "Defense Up S: Dark",
        "Defense Up D: Metal",
        "Defense Up C: Metal",
        "Defense Up B: Metal",
        "Defense Up A: Metal",
        "Defense Up S: Metal",
        "Attack Up D: Angel",
        "Attack Up C: Angel",
        "Attack Up B: Angel",
        "Attack Up A: Angel",
        "Attack Up S: Angel",
        "Defense Up D: Angel",
        "Defense Up C: Angel",
        "Defense Up B: Angel",
        "Defense Up A: Angel",
        "Defense Up S: Angel",
        "Attack Up D: Alien",
        "Attack Up C: Alien",
        "Attack Up B: Alien",
        "Attack Up A: Alien",
        "Attack Up S: Alien",
        "Defense Up D: Alien",
        "Defense Up C: Alien",
        "Defense Up B: Alien",
        "Defense Up A: Alien",
        "Defense Up S: Alien",
        "Attack Up D: Zombie",
        "Attack Up C: Zombie",
        "Attack Up B: Zombie",
        "Attack Up A: Zombie",
        "Attack Up S: Zombie",
        "Defense Up D: Zombie",
        "Defense Up C: Zombie",
        "Defense Up B: Zombie",
        "Defense Up A: Zombie",
        "Defense Up S: Zombie",
        "Strong Effect Up D: Red",
        "Strong Effect Up C: Red",
        "Strong Effect Up B: Red",
        "Strong Effect Up A: Red",
        "Strong Effect Up S: Red",
        "Massive Damage Up D: Red",
        "Massive Damage Up C: Red",
        "Massive Damage Up B: Red",
        "Massive Damage Up A: Red",
        "Massive Damage Up S: Red",
        "Tough Effect Up D: Red",
        "Tough Effect Up C: Red",
        "Tough Effect Up B: Red",
        "Tough Effect Up A: Red",
        "Tough Effect Up S: Red",
        "Strong Effect Up D: Floating",
        "Strong Effect Up C: Floating",
        "Strong Effect Up B: Floating",
        "Strong Effect Up A: Floating",
        "Strong Effect Up S: Floating",
        "Massive Damage Up D: Floating",
        "Massive Damage Up C: Floating",
        "Massive Damage Up B: Floating",
        "Massive Damage Up A: Floating",
        "Massive Damage Up S: Floating",
        "Tough Effect Up D: Floating",
        "Tough Effect Up C: Floating",
        "Tough Effect Up B: Floating",
        "Tough Effect Up A: Floating",
        "Tough Effect Up S: Floating",
        "Strong Effect Up D: Dark",
        "Strong Effect Up C: Dark",
        "Strong Effect Up B: Dark",
        "Strong Effect Up A: Dark",
        "Strong Effect Up S: Dark",
        "Massive Damage Up D: Dark",
        "Massive Damage Up C: Dark",
        "Massive Damage Up B: Dark",
        "Massive Damage Up A: Dark",
        "Massive Damage Up S: Dark",
        "Tough Effect Up D: Dark",
        "Tough Effect Up C: Dark",
        "Tough Effect Up B: Dark",
        "Tough Effect Up A: Dark",
        "Tough Effect Up S: Dark",
        "Strong Effect Up D: Angel",
        "Strong Effect Up C: Angel",
        "Strong Effect Up B: Angel",
        "Strong Effect Up A: Angel",
        "Strong Effect Up S: Angel",
        "Massive Damage Up D: Angel",
        "Massive Damage Up C: Angel",
        "Massive Damage Up B: Angel",
        "Massive Damage Up A: Angel",
        "Massive Damage Up S: Angel",
        "Tough Effect Up D: Angel",
        "Tough Effect Up C: Angel",
        "Tough Effect Up B: Angel",
        "Tough Effect Up A: Angel",
        "Tough Effect Up S: Angel",
        "Strong Effect Up D: Alien",
        "Strong Effect Up C: Alien",
        "Strong Effect Up B: Alien",
        "Strong Effect Up A: Alien",
        "Strong Effect Up S: Alien",
        "Massive Damage Up D: Alien",
        "Massive Damage Up C: Alien",
        "Massive Damage Up B: Alien",
        "Massive Damage Up A: Alien",
        "Massive Damage Up S: Alien",
        "Tough Effect Up D: Alien",
        "Tough Effect Up C: Alien",
        "Tough Effect Up B: Alien",
        "Tough Effect Up A: Alien",
        "Tough Effect Up S: Alien",
        "Strong Effect Up D: Zombie",
        "Strong Effect Up C: Zombie",
        "Strong Effect Up B: Zombie",
        "Strong Effect Up A: Zombie",
        "Strong Effect Up S: Zombie",
        "Massive Damage Up D: Zombie",
        "Massive Damage Up C: Zombie",
        "Massive Damage Up B: Zombie",
        "Massive Damage Up A: Zombie",
        "Massive Damage Up S: Zombie",
        "Tough Effect Up D: Zombie",
        "Tough Effect Up C: Zombie",
        "Tough Effect Up B: Zombie",
        "Tough Effect Up A: Zombie",
        "Tough Effect Up S: Zombie",
        "Attack Up D: Aku",
        "Attack Up C: Aku",
        "Attack Up B: Aku",
        "Attack Up A: Aku",
        "Attack Up S: Aku",
        "Defense Up D: Aku",
        "Defense Up C: Aku",
        "Defense Up B: Aku",
        "Defense Up A: Aku",
        "Defense Up S: Aku",
        "Strong Effect Up D: Aku",
        "Strong Effect Up C: Aku",
        "Strong Effect Up B: Aku",
        "Strong Effect Up A: Aku",
        "Strong Effect Up S: Aku",
        "Massive Damage Up D: Aku",
        "Massive Damage Up C: Aku",
        "Massive Damage Up B: Aku",
        "Massive Damage Up A: Aku",
        "Massive Damage Up S: Aku",
        "Tough Effect Up D: Aku",
        "Tough Effect Up C: Aku",
        "Tough Effect Up B: Aku",
        "Tough Effect Up A: Aku",
        "Tough Effect Up S: Aku",
        "Attack Up D: Relic",
        "Attack Up C: Relic",
        "Attack Up B: Relic",
        "Attack Up A: Relic",
        "Attack Up S: Relic",
        "Defense Up D: Relic",
        "Defense Up C: Relic",
        "Defense Up B: Relic",
        "Defense Up A: Relic",
        "Defense Up S: Relic",
        "Strong Effect Up D: Relic",
        "Strong Effect Up C: Relic",
        "Strong Effect Up B: Relic",
        "Strong Effect Up A: Relic",
        "Strong Effect Up S: Relic",
        "Massive Damage Up D: Relic",
        "Massive Damage Up C: Relic",
        "Massive Damage Up B: Relic",
        "Massive Damage Up A: Relic",
        "Massive Damage Up S: Relic",
        "Tough Effect Up D: Relic",
        "Tough Effect Up C: Relic",
        "Tough Effect Up B: Relic",
        "Tough Effect Up A: Relic",
        "Tough Effect Up S: Relic",
        "Mini-Death Surge D",
        "Mini-Death Surge C",
        "Mini-Death Surge B",
        "Mini-Death Surge A",
        "Mini-Death Surge S",
        "Resist Waves D",
        "Resist Waves C",
        "Resist Waves B",
        "Resist Waves A",
        "Resist Waves S",
        "Cash Back D",
        "Cash Back C",
        "Cash Back B",
        "Cash Back A",
        "Cash Back S",
        "Resist Knockback D",
        "Resist Knockback C",
        "Resist Knockback B",
        "Resist Knockback A",
        "Resist Knockback S",
        "Boost Stories of Legend D",
        "Boost Stories of Legend C",
        "Boost Stories of Legend B",
        "Boost Stories of Legend A",
        "Boost Stories of Legend S",
        "Colossus Slayer D",
        "Colossus Slayer C",
        "Colossus Slayer B",
        "Colossus Slayer A",
        "Colossus Slayer S",
        "Cat Cannon Charge D",
        "Cat Cannon Charge C",
        "Cat Cannon Charge B",
        "Cat Cannon Charge A",
        "Cat Cannon Charge S",
        "Resist Toxic D",
        "Resist Toxic C",
        "Resist Toxic B",
        "Resist Toxic A",
        "Resist Toxic S",
        "Dodge Attack (All) D",
        "Dodge Attack (All) C",
        "Dodge Attack (All) B",
        "Dodge Attack (All) A",
        "Dodge Attack (All) S",
        "Resist Slow D",
        "Resist Slow C",
        "Resist Slow B",
        "Resist Slow A",
        "Resist Slow S",
        "Resist Curse D",
        "Resist Curse C",
        "Resist Curse B",
        "Resist Curse A",
        "Resist Curse S",
        "Boost Uncanny Legends D",
        "Boost Uncanny Legends C",
        "Boost Uncanny Legends B",
        "Boost Uncanny Legends A",
        "Boost Uncanny Legends S",
        "Single Surge Counter D",
        "Single Surge Counter C",
        "Single Surge Counter B",
        "Single Surge Counter A",
        "Single Surge Counter S",
        "Berserker D",
        "Berserker C",
        "Berserker B",
        "Berserker A",
        "Berserker S",
        "Shortened Cooldown D",
        "Shortened Cooldown C",
        "Shortened Cooldown B",
        "Shortened Cooldown A",
        "Shortened Cooldown S",
        "Resist Freeze D",
        "Resist Freeze C",
        "Resist Freeze B",
        "Resist Freeze A",
        "Resist Freeze S",
        "Resist Weaken D",
        "Resist Weaken C",
        "Resist Weaken B",
        "Resist Weaken A",
        "Resist Weaken S",
        "Cost Down D",
        "Cost Down C",
        "Cost Down B",
        "Cost Down A",
        "Cost Down S",
        "Resist Surges D",
        "Resist Surges C",
        "Resist Surges B",
        "Resist Surges A",
        "Resist Surges S",
        "First Bounty Up D",
        "First Bounty Up C",
        "First Bounty Up B",
        "First Bounty Up A",
        "First Bounty Up S",
        "Resists Explosions D",
        "Resists Explosions C",
        "Resists Explosions B",
        "Resists Explosions A",
        "Resists Explosions S",
    };
    private static final String[] TW = {
        "提升傷害D【紅】",
        "提升傷害C【紅】",
        "提升傷害B【紅】",
        "提升傷害A【紅】",
        "提升傷害S【紅】",
        "減輕傷害D【紅】",
        "減輕傷害C【紅】",
        "減輕傷害B【紅】",
        "減輕傷害A【紅】",
        "減輕傷害S【紅】",
        "提升傷害D【浮】",
        "提升傷害C【浮】",
        "提升傷害B【浮】",
        "提升傷害A【浮】",
        "提升傷害S【浮】",
        "減輕傷害D【浮】",
        "減輕傷害C【浮】",
        "減輕傷害B【浮】",
        "減輕傷害A【浮】",
        "減輕傷害S【浮】",
        "提升傷害D【黑】",
        "提升傷害C【黑】",
        "提升傷害B【黑】",
        "提升傷害A【黑】",
        "提升傷害S【黑】",
        "減輕傷害D【黑】",
        "減輕傷害C【黑】",
        "減輕傷害B【黑】",
        "減輕傷害A【黑】",
        "減輕傷害S【黑】",
        "減輕傷害D【鋼】",
        "減輕傷害C【鋼】",
        "減輕傷害B【鋼】",
        "減輕傷害A【鋼】",
        "減輕傷害S【鋼】",
        "提升傷害D【天】",
        "提升傷害C【天】",
        "提升傷害B【天】",
        "提升傷害A【天】",
        "提升傷害S【天】",
        "減輕傷害D【天】",
        "減輕傷害C【天】",
        "減輕傷害B【天】",
        "減輕傷害A【天】",
        "減輕傷害S【天】",
        "提升傷害D【異】",
        "提升傷害C【異】",
        "提升傷害B【異】",
        "提升傷害A【異】",
        "提升傷害S【異】",
        "減輕傷害D【異】",
        "減輕傷害C【異】",
        "減輕傷害B【異】",
        "減輕傷害A【異】",
        "減輕傷害S【異】",
        "提升傷害D【死】",
        "提升傷害C【死】",
        "提升傷害B【死】",
        "提升傷害A【死】",
        "提升傷害S【死】",
        "減輕傷害D【死】",
        "減輕傷害C【死】",
        "減輕傷害B【死】",
        "減輕傷害A【死】",
        "減輕傷害S【死】",
        "強化善於攻擊D【紅】",
        "強化善於攻擊C【紅】",
        "強化善於攻擊B【紅】",
        "強化善於攻擊A【紅】",
        "強化善於攻擊S【紅】",
        "強化超大傷害D【紅】",
        "強化超大傷害C【紅】",
        "強化超大傷害B【紅】",
        "強化超大傷害A【紅】",
        "強化超大傷害S【紅】",
        "強化很耐打D【紅】",
        "強化很耐打C【紅】",
        "強化很耐打B【紅】",
        "強化很耐打A【紅】",
        "強化很耐打S【紅】",
        "強化善於攻擊D【浮】",
        "強化善於攻擊C【浮】",
        "強化善於攻擊B【浮】",
        "強化善於攻擊A【浮】",
        "強化善於攻擊S【浮】",
        "強化超大傷害D【浮】",
        "強化超大傷害C【浮】",
        "強化超大傷害B【浮】",
        "強化超大傷害A【浮】",
        "強化超大傷害S【浮】",
        "強化很耐打D【浮】",
        "強化很耐打C【浮】",
        "強化很耐打B【浮】",
        "強化很耐打A【浮】",
        "強化很耐打S【浮】",
        "強化善於攻擊D【黑】",
        "強化善於攻擊C【黑】",
        "強化善於攻擊B【黑】",
        "強化善於攻擊A【黑】",
        "強化善於攻擊S【黑】",
        "強化超大傷害D【黑】",
        "強化超大傷害C【黑】",
        "強化超大傷害B【黑】",
        "強化超大傷害A【黑】",
        "強化超大傷害S【黑】",
        "強化很耐打D【黑】",
        "強化很耐打C【黑】",
        "強化很耐打B【黑】",
        "強化很耐打A【黑】",
        "強化很耐打S【黑】",
        "強化善於攻擊D【天】",
        "強化善於攻擊C【天】",
        "強化善於攻擊B【天】",
        "強化善於攻擊A【天】",
        "強化善於攻擊S【天】",
        "強化超大傷害D【天】",
        "強化超大傷害C【天】",
        "強化超大傷害B【天】",
        "強化超大傷害A【天】",
        "強化超大傷害S【天】",
        "強化很耐打D【天】",
        "強化很耐打C【天】",
        "強化很耐打B【天】",
        "強化很耐打A【天】",
        "強化很耐打S【天】",
        "強化善於攻擊D【異】",
        "強化善於攻擊C【異】",
        "強化善於攻擊B【異】",
        "強化善於攻擊A【異】",
        "強化善於攻擊S【異】",
        "強化超大傷害D【異】",
        "強化超大傷害C【異】",
        "強化超大傷害B【異】",
        "強化超大傷害A【異】",
        "強化超大傷害S【異】",
        "強化很耐打D【異】",
        "強化很耐打C【異】",
        "強化很耐打B【異】",
        "強化很耐打A【異】",
        "強化很耐打S【異】",
        "強化善於攻擊D【死】",
        "強化善於攻擊C【死】",
        "強化善於攻擊B【死】",
        "強化善於攻擊A【死】",
        "強化善於攻擊S【死】",
        "強化超大傷害D【死】",
        "強化超大傷害C【死】",
        "強化超大傷害B【死】",
        "強化超大傷害A【死】",
        "強化超大傷害S【死】",
        "強化很耐打D【死】",
        "強化很耐打C【死】",
        "強化很耐打B【死】",
        "強化很耐打A【死】",
        "強化很耐打S【死】",
        "提升傷害D【惡】",
        "提升傷害C【惡】",
        "提升傷害B【惡】",
        "提升傷害A【惡】",
        "提升傷害S【惡】",
        "減輕傷害D【惡】",
        "減輕傷害C【惡】",
        "減輕傷害B【惡】",
        "減輕傷害A【惡】",
        "減輕傷害S【惡】",
        "強化善於攻擊D【惡】",
        "強化善於攻擊C【惡】",
        "強化善於攻擊B【惡】",
        "強化善於攻擊A【惡】",
        "強化善於攻擊S【惡】",
        "強化超大傷害D【惡】",
        "強化超大傷害C【惡】",
        "強化超大傷害B【惡】",
        "強化超大傷害A【惡】",
        "強化超大傷害S【惡】",
        "強化很耐打D【惡】",
        "強化很耐打C【惡】",
        "強化很耐打B【惡】",
        "強化很耐打A【惡】",
        "強化很耐打S【惡】",
        "提升傷害D【古】",
        "提升傷害C【古】",
        "提升傷害B【古】",
        "提升傷害A【古】",
        "提升傷害S【古】",
        "減輕傷害D【古】",
        "減輕傷害C【古】",
        "減輕傷害B【古】",
        "減輕傷害A【古】",
        "減輕傷害S【古】",
        "強化善於攻擊D【古】",
        "強化善於攻擊C【古】",
        "強化善於攻擊B【古】",
        "強化善於攻擊A【古】",
        "強化善於攻擊S【古】",
        "強化超大傷害D【古】",
        "強化超大傷害C【古】",
        "強化超大傷害B【古】",
        "強化超大傷害A【古】",
        "強化超大傷害S【古】",
        "強化很耐打D【古】",
        "強化很耐打C【古】",
        "強化很耐打B【古】",
        "強化很耐打A【古】",
        "強化很耐打S【古】",
        "遺留小烈波D",
        "遺留小烈波C",
        "遺留小烈波B",
        "遺留小烈波A",
        "遺留小烈波S",
        "抗波耐性D",
        "抗波耐性C",
        "抗波耐性B",
        "抗波耐性A",
        "抗波耐性S",
        "金錢回饋D",
        "金錢回饋C",
        "金錢回饋B",
        "金錢回饋A",
        "金錢回饋S",
        "抗飛耐性D",
        "抗飛耐性C",
        "抗飛耐性B",
        "抗飛耐性A",
        "抗飛耐性S",
        "傳奇故事強化D",
        "傳奇故事強化C",
        "傳奇故事強化B",
        "傳奇故事強化A",
        "傳奇故事強化S",
        "超生命體特效D",
        "超生命體特效C",
        "超生命體特效B",
        "超生命體特效A",
        "超生命體特效S",
        "貓咪砲充電D",
        "貓咪砲充電C",
        "貓咪砲充電B",
        "貓咪砲充電A",
        "貓咪砲充電S",
        "抗毒擊耐性D",
        "抗毒擊耐性C",
        "抗毒擊耐性B",
        "抗毒擊耐性A",
        "抗毒擊耐性S",
        "全攻擊無效D",
        "全攻擊無效C",
        "全攻擊無效B",
        "全攻擊無效A",
        "全攻擊無效S",
        "動慢耐性D",
        "動慢耐性C",
        "動慢耐性B",
        "動慢耐性A",
        "動慢耐性S",
        "抗古代詛咒耐性D",
        "抗古代詛咒耐性C",
        "抗古代詛咒耐性B",
        "抗古代詛咒耐性A",
        "抗古代詛咒耐性S",
        "真傳奇故事強化D",
        "真傳奇故事強化C",
        "真傳奇故事強化B",
        "真傳奇故事強化A",
        "真傳奇故事強化S",
        "1次烈波反擊D",
        "1次烈波反擊C",
        "1次烈波反擊B",
        "1次烈波反擊A",
        "1次烈波反擊S",
        "打倒敵人攻擊力上升D",
        "打倒敵人攻擊力上升C",
        "打倒敵人攻擊力上升B",
        "打倒敵人攻擊力上升A",
        "打倒敵人攻擊力上升S",
        "縮短生產時間D",
        "縮短生產時間C",
        "縮短生產時間B",
        "縮短生產時間A",
        "縮短生產時間S",
        "動止耐性D",
        "動止耐性C",
        "動止耐性B",
        "動止耐性A",
        "動止耐性S",
        "抗擊耐性D",
        "抗擊耐性C",
        "抗擊耐性B",
        "抗擊耐性A",
        "抗擊耐性S",
        "生產成本折扣D",
        "生產成本折扣C",
        "生產成本折扣B",
        "生產成本折扣A",
        "生產成本折扣S",
        "抗烈波耐性D",
        "抗烈波耐性C",
        "抗烈波耐性B",
        "抗烈波耐性A",
        "抗烈波耐性S",
        "得到很多金錢D（限一次）",
        "得到很多金錢C（限一次）",
        "得到很多金錢B（限一次）",
        "得到很多金錢A（限一次）",
        "得到很多金錢S（限一次）",
        "抗爆波耐性D",
        "抗爆波耐性C",
        "抗爆波耐性B",
        "抗爆波耐性A",
        "抗爆波耐性S",
    };
    private static final String[] JP = {
        "ダメージアップD【赤】",
        "ダメージアップC【赤】",
        "ダメージアップB【赤】",
        "ダメージアップA【赤】",
        "ダメージアップS【赤】",
        "ダメージ軽減D【赤】",
        "ダメージ軽減C【赤】",
        "ダメージ軽減B【赤】",
        "ダメージ軽減A【赤】",
        "ダメージ軽減S【赤】",
        "ダメージアップD【浮】",
        "ダメージアップC【浮】",
        "ダメージアップB【浮】",
        "ダメージアップA【浮】",
        "ダメージアップS【浮】",
        "ダメージ軽減D【浮】",
        "ダメージ軽減C【浮】",
        "ダメージ軽減B【浮】",
        "ダメージ軽減A【浮】",
        "ダメージ軽減S【浮】",
        "ダメージアップD【黒】",
        "ダメージアップC【黒】",
        "ダメージアップB【黒】",
        "ダメージアップA【黒】",
        "ダメージアップS【黒】",
        "ダメージ軽減D【黒】",
        "ダメージ軽減C【黒】",
        "ダメージ軽減B【黒】",
        "ダメージ軽減A【黒】",
        "ダメージ軽減S【黒】",
        "ダメージ軽減D【メ】",
        "ダメージ軽減C【メ】",
        "ダメージ軽減B【メ】",
        "ダメージ軽減A【メ】",
        "ダメージ軽減S【メ】",
        "ダメージアップD【天】",
        "ダメージアップC【天】",
        "ダメージアップB【天】",
        "ダメージアップA【天】",
        "ダメージアップS【天】",
        "ダメージ軽減D【天】",
        "ダメージ軽減C【天】",
        "ダメージ軽減B【天】",
        "ダメージ軽減A【天】",
        "ダメージ軽減S【天】",
        "ダメージアップD【エ】",
        "ダメージアップC【エ】",
        "ダメージアップB【エ】",
        "ダメージアップA【エ】",
        "ダメージアップS【エ】",
        "ダメージ軽減D【エ】",
        "ダメージ軽減C【エ】",
        "ダメージ軽減B【エ】",
        "ダメージ軽減A【エ】",
        "ダメージ軽減S【エ】",
        "ダメージアップD【ゾ】",
        "ダメージアップC【ゾ】",
        "ダメージアップB【ゾ】",
        "ダメージアップA【ゾ】",
        "ダメージアップS【ゾ】",
        "ダメージ軽減D【ゾ】",
        "ダメージ軽減C【ゾ】",
        "ダメージ軽減B【ゾ】",
        "ダメージ軽減A【ゾ】",
        "ダメージ軽減S【ゾ】",
        "めっぽう強い強化D【赤】",
        "めっぽう強い強化C【赤】",
        "めっぽう強い強化B【赤】",
        "めっぽう強い強化A【赤】",
        "めっぽう強い強化S【赤】",
        "超ダメージ強化D【赤】",
        "超ダメージ強化C【赤】",
        "超ダメージ強化B【赤】",
        "超ダメージ強化A【赤】",
        "超ダメージ強化S【赤】",
        "打たれ強い強化D【赤】",
        "打たれ強い強化C【赤】",
        "打たれ強い強化B【赤】",
        "打たれ強い強化A【赤】",
        "打たれ強い強化S【赤】",
        "めっぽう強い強化D【浮】",
        "めっぽう強い強化C【浮】",
        "めっぽう強い強化B【浮】",
        "めっぽう強い強化A【浮】",
        "めっぽう強い強化S【浮】",
        "超ダメージ強化D【浮】",
        "超ダメージ強化C【浮】",
        "超ダメージ強化B【浮】",
        "超ダメージ強化A【浮】",
        "超ダメージ強化S【浮】",
        "打たれ強い強化D【浮】",
        "打たれ強い強化C【浮】",
        "打たれ強い強化B【浮】",
        "打たれ強い強化A【浮】",
        "打たれ強い強化S【浮】",
        "めっぽう強い強化D【黒】",
        "めっぽう強い強化C【黒】",
        "めっぽう強い強化B【黒】",
        "めっぽう強い強化A【黒】",
        "めっぽう強い強化S【黒】",
        "超ダメージ強化D【黒】",
        "超ダメージ強化C【黒】",
        "超ダメージ強化B【黒】",
        "超ダメージ強化A【黒】",
        "超ダメージ強化S【黒】",
        "打たれ強い強化D【黒】",
        "打たれ強い強化C【黒】",
        "打たれ強い強化B【黒】",
        "打たれ強い強化A【黒】",
        "打たれ強い強化S【黒】",
        "めっぽう強い強化D【天】",
        "めっぽう強い強化C【天】",
        "めっぽう強い強化B【天】",
        "めっぽう強い強化A【天】",
        "めっぽう強い強化S【天】",
        "超ダメージ強化D【天】",
        "超ダメージ強化C【天】",
        "超ダメージ強化B【天】",
        "超ダメージ強化A【天】",
        "超ダメージ強化S【天】",
        "打たれ強い強化D【天】",
        "打たれ強い強化C【天】",
        "打たれ強い強化B【天】",
        "打たれ強い強化A【天】",
        "打たれ強い強化S【天】",
        "めっぽう強い強化D【エ】",
        "めっぽう強い強化C【エ】",
        "めっぽう強い強化B【エ】",
        "めっぽう強い強化A【エ】",
        "めっぽう強い強化S【エ】",
        "超ダメージ強化D【エ】",
        "超ダメージ強化C【エ】",
        "超ダメージ強化B【エ】",
        "超ダメージ強化A【エ】",
        "超ダメージ強化S【エ】",
        "打たれ強い強化D【エ】",
        "打たれ強い強化C【エ】",
        "打たれ強い強化B【エ】",
        "打たれ強い強化A【エ】",
        "打たれ強い強化S【エ】",
        "めっぽう強い強化D【ゾ】",
        "めっぽう強い強化C【ゾ】",
        "めっぽう強い強化B【ゾ】",
        "めっぽう強い強化A【ゾ】",
        "めっぽう強い強化S【ゾ】",
        "超ダメージ強化D【ゾ】",
        "超ダメージ強化C【ゾ】",
        "超ダメージ強化B【ゾ】",
        "超ダメージ強化A【ゾ】",
        "超ダメージ強化S【ゾ】",
        "打たれ強い強化D【ゾ】",
        "打たれ強い強化C【ゾ】",
        "打たれ強い強化B【ゾ】",
        "打たれ強い強化A【ゾ】",
        "打たれ強い強化S【ゾ】",
        "ダメージアップD【悪】",
        "ダメージアップC【悪】",
        "ダメージアップB【悪】",
        "ダメージアップA【悪】",
        "ダメージアップS【悪】",
        "ダメージ軽減D【悪】",
        "ダメージ軽減C【悪】",
        "ダメージ軽減B【悪】",
        "ダメージ軽減A【悪】",
        "ダメージ軽減S【悪】",
        "めっぽう強い強化D【悪】",
        "めっぽう強い強化C【悪】",
        "めっぽう強い強化B【悪】",
        "めっぽう強い強化A【悪】",
        "めっぽう強い強化S【悪】",
        "超ダメージ強化D【悪】",
        "超ダメージ強化C【悪】",
        "超ダメージ強化B【悪】",
        "超ダメージ強化A【悪】",
        "超ダメージ強化S【悪】",
        "打たれ強い強化D【悪】",
        "打たれ強い強化C【悪】",
        "打たれ強い強化B【悪】",
        "打たれ強い強化A【悪】",
        "打たれ強い強化S【悪】",
        "ダメージアップD【古】",
        "ダメージアップC【古】",
        "ダメージアップB【古】",
        "ダメージアップA【古】",
        "ダメージアップS【古】",
        "ダメージ軽減D【古】",
        "ダメージ軽減C【古】",
        "ダメージ軽減B【古】",
        "ダメージ軽減A【古】",
        "ダメージ軽減S【古】",
        "めっぽう強い強化D【古】",
        "めっぽう強い強化C【古】",
        "めっぽう強い強化B【古】",
        "めっぽう強い強化A【古】",
        "めっぽう強い強化S【古】",
        "超ダメージ強化D【古】",
        "超ダメージ強化C【古】",
        "超ダメージ強化B【古】",
        "超ダメージ強化A【古】",
        "超ダメージ強化S【古】",
        "打たれ強い強化D【古】",
        "打たれ強い強化C【古】",
        "打たれ強い強化B【古】",
        "打たれ強い強化A【古】",
        "打たれ強い強化S【古】",
        "デス小烈波D",
        "デス小烈波C",
        "デス小烈波B",
        "デス小烈波A",
        "デス小烈波S",
        "波動ダメージ耐性D",
        "波動ダメージ耐性C",
        "波動ダメージ耐性B",
        "波動ダメージ耐性A",
        "波動ダメージ耐性S",
        "キャッシュバックD",
        "キャッシュバックC",
        "キャッシュバックB",
        "キャッシュバックA",
        "キャッシュバックS",
        "ふっとばし耐性D",
        "ふっとばし耐性C",
        "ふっとばし耐性B",
        "ふっとばし耐性A",
        "ふっとばし耐性S",
        "レジェンドストーリー強化D",
        "レジェンドストーリー強化C",
        "レジェンドストーリー強化B",
        "レジェンドストーリー強化A",
        "レジェンドストーリー強化S",
        "超生命体特効D",
        "超生命体特効C",
        "超生命体特効B",
        "超生命体特効A",
        "超生命体特効S",
        "にゃんこ砲チャージD",
        "にゃんこ砲チャージC",
        "にゃんこ砲チャージB",
        "にゃんこ砲チャージA",
        "にゃんこ砲チャージS",
        "毒撃ダメージ耐性D",
        "毒撃ダメージ耐性C",
        "毒撃ダメージ耐性B",
        "毒撃ダメージ耐性A",
        "毒撃ダメージ耐性S",
        "全攻撃無効D",
        "全攻撃無効C",
        "全攻撃無効B",
        "全攻撃無効A",
        "全攻撃無効S",
        "動きを遅くする耐性D",
        "動きを遅くする耐性C",
        "動きを遅くする耐性B",
        "動きを遅くする耐性A",
        "動きを遅くする耐性S",
        "古代の呪い耐性D",
        "古代の呪い耐性C",
        "古代の呪い耐性B",
        "古代の呪い耐性A",
        "古代の呪い耐性S",
        "真レジェンドストーリー強化D",
        "真レジェンドストーリー強化C",
        "真レジェンドストーリー強化B",
        "真レジェンドストーリー強化A",
        "真レジェンドストーリー強化S",
        "１回烈波カウンターD",
        "１回烈波カウンターC",
        "１回烈波カウンターB",
        "１回烈波カウンターA",
        "１回烈波カウンターS",
        "撃破時攻撃力アップD",
        "撃破時攻撃力アップC",
        "撃破時攻撃力アップB",
        "撃破時攻撃力アップA",
        "撃破時攻撃力アップS",
        "生産時間短縮D",
        "生産時間短縮C",
        "生産時間短縮B",
        "生産時間短縮A",
        "生産時間短縮S",
        "動きを止める耐性D",
        "動きを止める耐性C",
        "動きを止める耐性B",
        "動きを止める耐性A",
        "動きを止める耐性S",
        "攻撃力ダウン耐性D",
        "攻撃力ダウン耐性C",
        "攻撃力ダウン耐性B",
        "攻撃力ダウン耐性A",
        "攻撃力ダウン耐性S",
        "生産コスト割引D",
        "生産コスト割引C",
        "生産コスト割引B",
        "生産コスト割引A",
        "生産コスト割引S",
        "烈波ダメージ耐性D",
        "烈波ダメージ耐性C",
        "烈波ダメージ耐性B",
        "烈波ダメージ耐性A",
        "烈波ダメージ耐性S",
        "初回撃破時お金アップD",
        "初回撃破時お金アップC",
        "初回撃破時お金アップB",
        "初回撃破時お金アップA",
        "初回撃破時お金アップS",
        "爆波ダメージ耐性D",
        "爆波ダメージ耐性C",
        "爆波ダメージ耐性B",
        "爆波ダメージ耐性A",
        "爆波ダメージ耐性S",
    };
    private static final String[] KR = {
        "데미지 업 D【빨】",
        "데미지 업 C【빨】",
        "데미지 업 B【빨】",
        "데미지 업 A【빨】",
        "데미지 업 S【빨】",
        "데미지 경감 D【빨】",
        "데미지 경감 C【빨】",
        "데미지 경감 B【빨】",
        "데미지 경감 A【빨】",
        "데미지 경감 S【빨】",
        "데미지 업 D【떠】",
        "데미지 업 C【떠】",
        "데미지 업 B【떠】",
        "데미지 업 A【떠】",
        "데미지 업 S【떠】",
        "데미지 경감 D【떠】",
        "데미지 경감 C【떠】",
        "데미지 경감 B【떠】",
        "데미지 경감 A【떠】",
        "데미지 경감 S【떠】",
        "데미지 업 D【검】",
        "데미지 업 C【검】",
        "데미지 업 B【검】",
        "데미지 업 A【검】",
        "데미지 업 S【검】",
        "데미지 경감 D【검】",
        "데미지 경감 C【검】",
        "데미지 경감 B【검】",
        "데미지 경감 A【검】",
        "데미지 경감 S【검】",
        "데미지 경감 D【메】",
        "데미지 경감 C【메】",
        "데미지 경감 B【메】",
        "데미지 경감 A【메】",
        "데미지 경감 S【메】",
        "데미지 업 D【천】",
        "데미지 업 C【천】",
        "데미지 업 B【천】",
        "데미지 업 A【천】",
        "데미지 업 S【천】",
        "데미지 경감 D【천】",
        "데미지 경감 C【천】",
        "데미지 경감 B【천】",
        "데미지 경감 A【천】",
        "데미지 경감 S【천】",
        "데미지 업 D【에】",
        "데미지 업 C【에】",
        "데미지 업 B【에】",
        "데미지 업 A【에】",
        "데미지 업 S【에】",
        "데미지 경감 D【에】",
        "데미지 경감 C【에】",
        "데미지 경감 B【에】",
        "데미지 경감 A【에】",
        "데미지 경감 S【에】",
        "데미지 업 D【좀】",
        "데미지 업 C【좀】",
        "데미지 업 B【좀】",
        "데미지 업 A【좀】",
        "데미지 업 S【좀】",
        "데미지 경감 D【좀】",
        "데미지 경감 C【좀】",
        "데미지 경감 B【좀】",
        "데미지 경감 A【좀】",
        "데미지 경감 S【좀】",
        "엄청 강하다 강화 D【빨】",
        "엄청 강하다 강화 C【빨】",
        "엄청 강하다 강화 B【빨】",
        "엄청 강하다 강화 A【빨】",
        "엄청 강하다 강화 S【빨】",
        "초 데미지 강화 D【빨】",
        "초 데미지 강화 C【빨】",
        "초 데미지 강화 B【빨】",
        "초 데미지 강화 A【빨】",
        "초 데미지 강화 S【빨】",
        "맷집이 좋다 강화 D【빨】",
        "맷집이 좋다 강화 C【빨】",
        "맷집이 좋다 강화 B【빨】",
        "맷집이 좋다 강화 A【빨】",
        "맷집이 좋다 강화 S【빨】",
        "엄청 강하다 강화 D【떠】",
        "엄청 강하다 강화 C【떠】",
        "엄청 강하다 강화 B【떠】",
        "엄청 강하다 강화 A【떠】",
        "엄청 강하다 강화 S【떠】",
        "초 데미지 강화 D【떠】",
        "초 데미지 강화 C【떠】",
        "초 데미지 강화 B【떠】",
        "초 데미지 강화 A【떠】",
        "초 데미지 강화 S【떠】",
        "맷집이 좋다 강화 D【떠】",
        "맷집이 좋다 강화 C【떠】",
        "맷집이 좋다 강화 B【떠】",
        "맷집이 좋다 강화 A【떠】",
        "맷집이 좋다 강화 S【떠】",
        "엄청 강하다 강화 D【검】",
        "엄청 강하다 강화 C【검】",
        "엄청 강하다 강화 B【검】",
        "엄청 강하다 강화 A【검】",
        "엄청 강하다 강화 S【검】",
        "초 데미지 강화 D【검】",
        "초 데미지 강화 C【검】",
        "초 데미지 강화 B【검】",
        "초 데미지 강화 A【검】",
        "초 데미지 강화 S【검】",
        "맷집이 좋다 강화 D【검】",
        "맷집이 좋다 강화 C【검】",
        "맷집이 좋다 강화 B【검】",
        "맷집이 좋다 강화 A【검】",
        "맷집이 좋다 강화 S【검】",
        "엄청 강하다 강화 D【천】",
        "엄청 강하다 강화 C【천】",
        "엄청 강하다 강화 B【천】",
        "엄청 강하다 강화 A【천】",
        "엄청 강하다 강화 S【천】",
        "초 데미지 강화 D【천】",
        "초 데미지 강화 C【천】",
        "초 데미지 강화 B【천】",
        "초 데미지 강화 A【천】",
        "초 데미지 강화 S【천】",
        "맷집이 좋다 강화 D【천】",
        "맷집이 좋다 강화 C【천】",
        "맷집이 좋다 강화 B【천】",
        "맷집이 좋다 강화 A【천】",
        "맷집이 좋다 강화 S【천】",
        "엄청 강하다 강화 D【에】",
        "엄청 강하다 강화 C【에】",
        "엄청 강하다 강화 B【에】",
        "엄청 강하다 강화 A【에】",
        "엄청 강하다 강화 S【에】",
        "초 데미지 강화 D【에】",
        "초 데미지 강화 C【에】",
        "초 데미지 강화 B【에】",
        "초 데미지 강화 A【에】",
        "초 데미지 강화 S【에】",
        "맷집이 좋다 강화 D【에】",
        "맷집이 좋다 강화 C【에】",
        "맷집이 좋다 강화 B【에】",
        "맷집이 좋다 강화 A【에】",
        "맷집이 좋다 강화 S【에】",
        "엄청 강하다 강화 D【좀】",
        "엄청 강하다 강화 C【좀】",
        "엄청 강하다 강화 B【좀】",
        "엄청 강하다 강화 A【좀】",
        "엄청 강하다 강화 S【좀】",
        "초 데미지 강화 D【좀】",
        "초 데미지 강화 C【좀】",
        "초 데미지 강화 B【좀】",
        "초 데미지 강화 A【좀】",
        "초 데미지 강화 S【좀】",
        "맷집이 좋다 강화 D【좀】",
        "맷집이 좋다 강화 C【좀】",
        "맷집이 좋다 강화 B【좀】",
        "맷집이 좋다 강화 A【좀】",
        "맷집이 좋다 강화 S【좀】",
        "데미지 업 D【악】",
        "데미지 업 C【악】",
        "데미지 업 B【악】",
        "데미지 업 A【악】",
        "데미지 업 S【악】",
        "데미지 경감 D【악】",
        "데미지 경감 C【악】",
        "데미지 경감 B【악】",
        "데미지 경감 A【악】",
        "데미지 경감 S【악】",
        "엄청 강하다 강화 D【악】",
        "엄청 강하다 강화 C【악】",
        "엄청 강하다 강화 B【악】",
        "엄청 강하다 강화 A【악】",
        "엄청 강하다 강화 S【악】",
        "초 데미지 강화 D【악】",
        "초 데미지 강화 C【악】",
        "초 데미지 강화 B【악】",
        "초 데미지 강화 A【악】",
        "초 데미지 강화 S【악】",
        "맷집이 좋다 강화 D【악】",
        "맷집이 좋다 강화 C【악】",
        "맷집이 좋다 강화 B【악】",
        "맷집이 좋다 강화 A【악】",
        "맷집이 좋다 강화 S【악】",
        "데미지 업 D【고】",
        "데미지 업 C【고】",
        "데미지 업 B【고】",
        "데미지 업 A【고】",
        "데미지 업 S【고】",
        "데미지 경감 D【고】",
        "데미지 경감 C【고】",
        "데미지 경감 B【고】",
        "데미지 경감 A【고】",
        "데미지 경감 S【고】",
        "엄청 강하다 강화 D【고】",
        "엄청 강하다 강화 C【고】",
        "엄청 강하다 강화 B【고】",
        "엄청 강하다 강화 A【고】",
        "엄청 강하다 강화 S【고】",
        "초 데미지 강화 D【고】",
        "초 데미지 강화 C【고】",
        "초 데미지 강화 B【고】",
        "초 데미지 강화 A【고】",
        "초 데미지 강화 S【고】",
        "맷집이 좋다 강화 D【고】",
        "맷집이 좋다 강화 C【고】",
        "맷집이 좋다 강화 B【고】",
        "맷집이 좋다 강화 A【고】",
        "맷집이 좋다 강화 S【고】",
        "데스 소열파 D",
        "데스 소열파 C",
        "데스 소열파 B",
        "데스 소열파 A",
        "데스 소열파 S",
        "파동 데미지 내성 D",
        "파동 데미지 내성 C",
        "파동 데미지 내성 B",
        "파동 데미지 내성 A",
        "파동 데미지 내성 S",
        "캐시백 D",
        "캐시백 C",
        "캐시백 B",
        "캐시백 A",
        "캐시백 S",
        "날려버린다 내성 D",
        "날려버린다 내성 C",
        "날려버린다 내성 B",
        "날려버린다 내성 A",
        "날려버린다 내성 S",
        "레전드 스토리 강화 D",
        "레전드 스토리 강화 C",
        "레전드 스토리 강화 B",
        "레전드 스토리 강화 A",
        "레전드 스토리 강화 S",
        "초생명체 특효 D",
        "초생명체 특효 C",
        "초생명체 특효 B",
        "초생명체 특효 A",
        "초생명체 특효 S",
        "냥코 대포 충전 D",
        "냥코 대포 충전 C",
        "냥코 대포 충전 B",
        "냥코 대포 충전 A",
        "냥코 대포 충전 S",
        "독 공격 데미지 내성 D",
        "독 공격 데미지 내성 C",
        "독 공격 데미지 내성 B",
        "독 공격 데미지 내성 A",
        "독 공격 데미지 내성 S",
        "전 공격 무효 D",
        "전 공격 무효 C",
        "전 공격 무효 B",
        "전 공격 무효 A",
        "전 공격 무효 S",
        "움직임을 느리게 한다 내성 D",
        "움직임을 느리게 한다 내성 C",
        "움직임을 느리게 한다 내성 B",
        "움직임을 느리게 한다 내성 A",
        "움직임을 느리게 한다 내성 S",
        "고대의 저주 내성 D",
        "고대의 저주 내성 C",
        "고대의 저주 내성 B",
        "고대의 저주 내성 A",
        "고대의 저주 내성 S",
        "신 레전드 스토리 강화 D",
        "신 레전드 스토리 강화 C",
        "신 레전드 스토리 강화 B",
        "신 레전드 스토리 강화 A",
        "신 레전드 스토리 강화 S",
        "1회 열파 카운터 D",
        "1회 열파 카운터 C",
        "1회 열파 카운터 B",
        "1회 열파 카운터 A",
        "1회 열파 카운터 S",
        "격파 시 공격력 업 D",
        "격파 시 공격력 업 C",
        "격파 시 공격력 업 B",
        "격파 시 공격력 업 A",
        "격파 시 공격력 업 S",
        "생산 시간 단축 D",
        "생산 시간 단축 C",
        "생산 시간 단축 B",
        "생산 시간 단축 A",
        "생산 시간 단축 S",
        "움직임을 멈춘다 내성 D",
        "움직임을 멈춘다 내성 C",
        "움직임을 멈춘다 내성 B",
        "움직임을 멈춘다 내성 A",
        "움직임을 멈춘다 내성 S",
        "공격력 다운 내성 D",
        "공격력 다운 내성 C",
        "공격력 다운 내성 B",
        "공격력 다운 내성 A",
        "공격력 다운 내성 S",
        "생산 코스트 할인 D",
        "생산 코스트 할인 C",
        "생산 코스트 할인 B",
        "생산 코스트 할인 A",
        "생산 코스트 할인 S",
        "열파 데미지 내성 D",
        "열파 데미지 내성 C",
        "열파 데미지 내성 B",
        "열파 데미지 내성 A",
        "열파 데미지 내성 S",
        "첫 격파 시 머니 UP D",
        "첫 격파 시 머니 UP C",
        "첫 격파 시 머니 UP B",
        "첫 격파 시 머니 UP A",
        "첫 격파 시 머니 UP S",
        "폭파 데미지 내성 D",
        "폭파 데미지 내성 C",
        "폭파 데미지 내성 B",
        "폭파 데미지 내성 A",
        "폭파 데미지 내성 S",
    };
    private static final int[] GRADE = {0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
    private static final int[] EFFECT = {0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25};
    private static final int[] ATTRIBUTE = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1};
    static int grade(int id) { return id >= 0 && id < GRADE.length ? GRADE[id] : -1; }
    static int effect(int id) { return id >= 0 && id < EFFECT.length ? EFFECT[id] : -1; }
    static int attribute(int id) { return id >= 0 && id < ATTRIBUTE.length ? ATTRIBUTE[id] : -1; }
    static String name(SaveDocument.Region region, int id) {
        String[] names = switch (region) {
            case JP -> JP;
            case TW -> TW;
            case KR -> KR;
            case EN -> EN;
        };
        return id >= 0 && id < names.length ? names[id] : null;
    }
}
